---
- name: install docker prereqs
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ca-certificates
      - curl
      - gnupg

- name: docker apt key
  shell:
    cmd: curl https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker-archive-keyring.pgp
    creates: /etc/apt/keyrings/docker-archive-keyring.pgp

- name: docker apt repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker-archive-keyring.pgp] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable
    state: present
    filename: docker

- name: install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin

- name: ensure docker group exists
  group:
    name: docker

- name: add my user to docker group
  user:
    name: davido
    groups: docker
    append: yes

- name: start docker service
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started

- name: start containerd service
  ansible.builtin.service:
    name: containerd
    enabled: yes
    state: started
